version: "3"

services:
  server:
    build:
      context: .
      dockerfile: ./docker/server/Dockerfile
    container_name: "${APP_NAME}-server"
    ports:
      - "${APP_PORT}:80"
    environment:
      - "DATABASE_URL=mysql://${MYSQL_USER}:${MYSQL_PASS}@db_server:3306/${MYSQL_DB}?serverVersion=10.5"
      - "NGINX_BACKEND_DOMAIN=${APP_DOMAIN}"
    volumes:
      - ./codebase-api:/var/www/html
      - ./docker/server/nginx/sites-enabled:/etc/nginx/conf.d/
      - ./docker/server/php/php.ini:/usr/local/etc/php/conf.d/extra-php-config.ini
      - ./docker/server/logs:/var/log/nginx
      - ./docker/server/scripts:/scripts
    command: >
      /bin/sh "/scripts/composer.sh" &&
      /bin/sh "/scripts/init-data-test.sh" &&
      /bin/sh "/scripts/init-data-dev.sh" &&
    #/bin/sh "/scripts/run-tests.sh"
    depends_on:
      - db_server
    networks:
      - phone_book_app_net

  db_server:
    image: mariadb:10.5.9
    container_name: "${APP_NAME}-db"
    restart: always
    ports:
      - "${DB_PORT}:3306"
    environment:
      MYSQL_ROOT_PASSWORD: "${MYSQL_ROOT_PASS}"
      MYSQL_USER: "${MYSQL_USER}"
      MYSQL_PASSWORD: "${MYSQL_PASS}"
      MYSQL_DATABASE: "${MYSQL_DB}"
    volumes:
      - db_data:/var/lib/mysql
      - ./docker/db/mariadb/my.cnf:/etc/mysql/conf.d/my.cnf
    healthcheck:
      test: mysqladmin ping -h 127.0.0.1 -u root --password=$$MYSQL_ROOT_PASSWORD
      interval: 5s
      retries: 5
    networks:
      - phone_book_app_net

  db_admin:
    image: phpmyadmin/phpmyadmin:5
    container_name: "${APP_NAME}-db-admin"
    ports:
      - "${APP_DB_ADMIN_PORT}:80"
    environment:
      PMA_HOST: db_server
    depends_on:
      - db_server
    volumes:
      - db_admin_data:/var/www/html
    networks:
      - phone_book_app_net

volumes:
  db_data:
  db_admin_data:

networks:
  phone_book_app_net:
